### PR TITLE
Make sure to not report a warning if no tests were found

### LINKED ISSUE #102: Show "nothing to test" instead of warning
When there's nothing to test for a PR; the following warning is shown:

image

This might give the impression that CI failed, while it didn't. Instead, we should show something like:

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:white_check_mark:</td>
      <td>No tests found for the current changes</td>
    </tr>
  </tbody>
</table>

### PR DESCRIPTION
**Pull request by AvdLee**
Just a little improvement in the Danger messaging.

Fixes #102

### CODE REVIEW

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Testing cancelled because the build failed.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Swift package target 'Danger' is linked as a static library by 'WeTransferPRLinterTests' and 'Danger', but cannot be built dynamically because there is a package product with the same name.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/da0790b0-f9c4-44d2-bdd8-d720a34db709" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 795099f8b1b0540f14cc16a171dc17f31f12f57e
</p>

File: WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift [hunk 1]
```diff
@@ -72,6 +72,8 @@ public enum WeTransferPRLinter {
 
                 return true
             }
+        } catch let error as LocationError where error.isMissingError {
```
Comment (kairadiagne) [inline WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift:75]: Nit: would it make sense to do `error.reason == .missing`. For example, it would enable someone who reads the code to lookup documentation by clicking on the `.missing` part.

**Review by kairadiagne — APPROVED** [review]

File: WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift (hunk 1 above)
Comment (AvdLee) [reply WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift:75]: Yeah, I started with that but `LocationErrorReason` does not conform to `Equatable` which is why I went for this route. Easier to maintain since we don't own the library including `LocationErrorReason`.
