### PR TITLE
Disable file and line reporting to fix Danger warning and error reports

### LINKED ISSUE #145: Bitrise can report "green" even when the build fails
Also, Danger has been having issues reporting the actual errors that happen. Is that something we can improve?

In some pull requests:

- Bitrise was green
- Danger was red, but only "because the build failed"

image

Whereas the actual errors occur in e.g. a test target where things don't compile because the API was changed.

### PR DESCRIPTION
**Pull request by AvdLee**
See this issue for more context: https://github.com/danger/swift/issues/513#issuecomment-1099137770

Basically; after GH introduced [their new PR experience](https://github.com/github/feedback/discussions/12341), things started to break on our side. The ability to report errors and warnings inline seems to be broken, so I temporarily disabled this feature for now.

### Running Danger locally
Testing and debugging Danger can be difficult sometimes, so I decided to create a `fastlane run_danger_locally` lane which simplifies this by a lot.

Fixes #145

### CODE REVIEW

**Review by BasThomas — APPROVED** [review]

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  `danger-swift` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
/Users/vagrant/git/.build/debug/WeTransferPRLinter.build/module.modulemap:2:12: error: header '/Users/vagrant/git/.build/x86_64-apple-macosx/debug/WeTransferPRLinter.build/WeTransferPRLinter-Swift.h' not found
    header "/Users/vagrant/git/.build/x86_64-apple-macosx/debug/WeTransferPRLinter.build/WeTransferPRLinter-Swift.h"
           ^
/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/_tmp_dangerfile.swift:2:8: error: could not build Objective-C module 'WeTransferPRLinter'
import WeTransferPRLinter
       ^
[31mERROR: Dangerfile eval failed at Dangerfile.swift
[0;0m[31mERROR: Could not get the results JSON file at /var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/danger-response.json
[0;0m
```

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a17b165a0337e0f089778b2f6e31dfa7de7f81fa
</p>

**Comment by AvdLee** [comment]
Merging this in since Danger is currently failing due to GitHub issues.

File: WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift [hunk 1]
```diff
@@ -50,8 +50,10 @@ final class XCResultSummartReporterTests: XCTestCase {
         XCTAssertEqual(danger.fails.count, 2)
         let failure = try XCTUnwrap(danger.fails.first)
         XCTAssertEqual(failure.message, "**TestTests.testFailureJosh1():**<br/>XCTAssertTrue failed")
-        XCTAssertEqual(failure.file, "test-ios/TestTests/TestTests.swift")
-        XCTAssertEqual(failure.line, 36)
+
+        // Enable once inline reporting works again.
```
Comment (peagasilva) [inline WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift:54]: It just occurred to me: should it be updated to a warning?

Comment (AvdLee) [reply WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift:54]: Agreed! I rewrote this in an upcoming PR using expected failure:
image
